name: Upload artifact
on: workflow_call
jobs:
  upload-artifact:
    name: Upload artifact
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        if: '${{ !cancelled() }}'
        with:
          name: playwright-report
          path: ./../playwright-report/
          retention-days: 30